---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels: 
    app: rails
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP

  selector:
    app: rails
    tier: database
