apiVersion: v1
kind: PersistentVolume
metadata:
  name: drkiq-postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: drkiq-redis
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
