---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app: rails
    spec:
      volumes:
      - name: drkiq-postgres
      containers:
      - name: postgres
        image: postgres:9.4.5
        env:
        - name: POSTGRES_USER
          value: drkiq
        - name: POSTGRES_PASSWORD
          value: yourpassword
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: drkiq-postgres