---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: rails
      tier: app
  template:
    metadata:
      name: redis
      labels:
        app: rails
        tier: app
    spec:
      volumes:
      - name: pdrkiq-redis
        persistentVolumeClaim:
          claimName: pdrkiq-redis-claim
      containers:
      - name: redis
        image: redis:3.0.5
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/var/lib/redis/data"
          name: pdrkiq-redis   